### ISSUE TITLE
Change Read.ME instructions

### ISSUE THREAD

**Issue by yantsa** [vigrai/zabbix-template-php-fpm#1]
Thanks for your great template. I has an issue when followed the Read.Me file instructions. 

The Item, **PHP-FPM Pools Discovery: PHP-FPM Pool www status page** was failing with a 403 error . I found out that, since the http check is performed by zabbix server or proxy it would eventually fail due to disallow access on nginx example 

  allow 127.0.0.1; 
  deny all;

with the above config it doesn't allow zabbix agent or zabbix server to perform the http check. You to either remove above 2 lines (ugly) or give instructions for allowing zabbix server or proxy IPs .

**Comment by fgallese** [comment]
Hello @yantsa thank you for the feedback ! I agree with you, when I wrote I had in mind using it on the same server, that's why I put 127.0.0.1. 
I'll update the readme to include a note to change this IP for your zabbix server/proxy from where you are doing the polling.
